name: Backend CI

on:
  push:
    paths:
      - backend
    branches: [ "main" ]
  pull_request:
    paths:
      - backend
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  backend-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy

    - name: Lint
      run: cargo clippy --all -- -D warnings
    - name: Build
      run:  cargo build --verbose
    - name: Run tests
      run: cargo test --verbose